#!/usr/bin/env node
/**
 * seo-report.mjs — Aggregate all SEO checks into a markdown report.
 *
 * Usage:
 *   node tools/seo-optimizer/seo-report.mjs --dist ./dist --format markdown
 *   node tools/seo-optimizer/seo-report.mjs --dist ./dist --format json
 *   node tools/seo-optimizer/seo-report.mjs --dist ./dist --output ./data/seo-report.md
 */

import { parseArgs } from 'node:util';
import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dir = fileURLToPath(new URL('.', import.meta.url));

const { values } = parseArgs({
  options: {
    dist:   { type: 'string', default: './dist' },
    format: { type: 'string', default: 'markdown' },
    output: { type: 'string', default: '' },
  },
  strict: false,
});

function runCheck(script, args = '') {
  try {
    const out = execSync(`node ${join(__dir, script)} --dist ${values.dist} --format json ${args}`, {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return { ok: true, data: JSON.parse(out) };
  } catch (err) {
    const out = err.stdout ?? '';
    try { return { ok: false, data: JSON.parse(out) }; } catch { return { ok: false, data: null, error: err.message }; }
  }
}

const date = new Date().toISOString().slice(0, 10);

console.log('Running SEO checks…');

const metaResult = runCheck('meta-audit.mjs');
const linkResult = runCheck('link-checker.mjs');
const robotsResult = runCheck('robots-validator.mjs', `--robots ./public/robots.txt`);

const metaData = metaResult.data ?? [];
const linkData = linkResult.data ?? { total: 0, broken: [] };

const totalPages = metaData.length;
const passingPages = metaData.filter((p) => p.score === p.total).length;
const metaScore = totalPages > 0 ? Math.round((passingPages / totalPages) * 100) : 100;
const brokenLinks = linkData.broken ?? [];
const robotsOk = robotsResult.ok;

const overallScore = Math.round((metaScore + (brokenLinks.length === 0 ? 100 : 0) + (robotsOk ? 100 : 0)) / 3);

if (values.format === 'json') {
  const report = { date, overallScore, metaScore, brokenLinks: brokenLinks.length, robotsOk, pages: metaData };
  const out = JSON.stringify(report, null, 2);
  if (values.output) { writeFileSync(values.output, out + '\n'); console.log(`Saved → ${values.output}`); }
  else console.log(out);
  process.exit(overallScore < 80 ? 1 : 0);
}

// Markdown format
const lines = [
  `# SEO Report — ${date}`,
  '',
  `## Overall Score: ${overallScore}/100`,
  '',
  '| Check | Score | Status |',
  '|-------|-------|--------|',
  `| Meta tags | ${metaScore}% | ${metaScore === 100 ? '✅' : '⚠️'} |`,
  `| Internal links | ${brokenLinks.length === 0 ? '100%' : `${brokenLinks.length} broken`} | ${brokenLinks.length === 0 ? '✅' : '❌'} |`,
  `| robots.txt | ${robotsOk ? 'Pass' : 'Issues'} | ${robotsOk ? '✅' : '❌'} |`,
  '',
];

// Meta issues
const failing = metaData.filter((p) => p.score < p.total);
if (failing.length > 0) {
  lines.push('## Meta Tag Issues', '');
  for (const page of failing) {
    const HTML_CHECKS = ['title', 'description', 'og_title', 'og_description', 'og_image', 'canonical', 'jsonld'];
    const missing = HTML_CHECKS.filter((c) => !page.checks[c]);
    lines.push(`### \`${page.page}\` (${page.score}/${page.total})`);
    lines.push(...missing.map((m) => `- ✗ Missing: ${m}`));
    lines.push('');
  }
} else {
  lines.push('## Meta Tags', '', '✅ All pages have complete meta tags.', '');
}

// Broken links
if (brokenLinks.length > 0) {
  lines.push('## Broken Internal Links', '');
  for (const { page, href } of brokenLinks) {
    lines.push(`- \`${page}\` → \`${href}\``);
  }
  lines.push('');
}

// robots.txt
lines.push('## robots.txt', '');
lines.push(robotsOk ? '✅ robots.txt is valid.' : '⚠️ robots.txt has issues (see robots-validator output for details).');
lines.push('');

// Footer
lines.push(`---`, `_Generated by tools/seo-optimizer/seo-report.mjs on ${date}_`);

const md = lines.join('\n');

if (values.output) {
  mkdirSync(dirname(values.output), { recursive: true });
  writeFileSync(values.output, md + '\n', 'utf8');
  console.log(`SEO report saved → ${values.output}`);
} else {
  console.log(md);
}

process.exit(overallScore < 80 ? 1 : 0);
