#!/usr/bin/env node
import { Command } from 'commander';
import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dir = fileURLToPath(new URL('.', import.meta.url));

const program = new Command();

program
  .option('--dist <path>', 'Path to built site directory', './dist')
  .option('--vendors <path>', 'Path to vendor markdown files', './src/content/vendors')
  .option('--output <path>', 'Write report to this file (default: stdout)', '')
  .parse(process.argv);

const opts = program.opts();

function runCheck(script, args = '') {
  try {
    const out = execSync(`node ${join(__dir, script)} --dist ${opts.dist} --format json ${args}`, {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return { ok: true, data: JSON.parse(out) };
  } catch (err) {
    const out = err.stdout ?? '';
    try { return { ok: false, data: JSON.parse(out) }; } catch { return { ok: false, data: null }; }
  }
}

const date = new Date().toISOString().slice(0, 10);

console.log('Running SEO checks…');

const metaResult = runCheck('meta-audit.mjs');
const linkResult = runCheck('link-checker.mjs');
const robotsResult = runCheck('robots-validator.mjs', `--robots ./public/robots.txt`);

const metaData = metaResult.data ?? [];
const linkData = linkResult.data ?? { total: 0, broken: [] };

const totalPages = metaData.length;
const passingPages = metaData.filter((p) => p.score === p.total).length;
const metaScore = totalPages > 0 ? Math.round((passingPages / totalPages) * 100) : 100;
const brokenLinks = linkData.broken ?? [];
const robotsOk = robotsResult.ok;

const overallScore = Math.round((metaScore + (brokenLinks.length === 0 ? 100 : 0) + (robotsOk ? 100 : 0)) / 3);

const lines = [
  `# SEO Report — ${date}`,
  '',
  `## Overall Score: ${overallScore}/100`,
  '',
  '| Check | Score | Status |',
  '|-------|-------|--------|',
  `| Meta tags | ${metaScore}% | ${metaScore === 100 ? '✅' : '⚠️'} |`,
  `| Internal links | ${brokenLinks.length === 0 ? '100%' : `${brokenLinks.length} broken`} | ${brokenLinks.length === 0 ? '✅' : '❌'} |`,
  `| robots.txt | ${robotsOk ? 'Pass' : 'Issues'} | ${robotsOk ? '✅' : '❌'} |`,
  '',
];

const failing = metaData.filter((p) => p.score < p.total);
if (failing.length > 0) {
  lines.push('## Meta Tag Issues', '');
  for (const page of failing) {
    const checks = ['title', 'description', 'og_title', 'og_description', 'og_image', 'canonical', 'jsonld'];
    const missing = checks.filter((c) => !page.checks?.[c]);
    lines.push(`### \`${page.page}\` (${page.score}/${page.total})`);
    lines.push(...missing.map((m) => `- ✗ Missing: ${m}`));
    lines.push('');
  }
} else {
  lines.push('## Meta Tags', '', '✅ All pages have complete meta tags.', '');
}

if (brokenLinks.length > 0) {
  lines.push('## Broken Internal Links', '');
  for (const { page, href } of brokenLinks) {
    lines.push(`- \`${page}\` → \`${href}\``);
  }
  lines.push('');
}

lines.push('## robots.txt', '');
lines.push(robotsOk ? '✅ robots.txt is valid.' : '⚠️ robots.txt has issues.');
lines.push('', `---`, `_Generated by tools/seo-optimizer/seo-report.mjs on ${date}_`);

const md = lines.join('\n');

if (opts.output) {
  mkdirSync(dirname(opts.output), { recursive: true });
  writeFileSync(opts.output, md + '\n', 'utf8');
  console.log(`SEO report saved → ${opts.output}`);
} else {
  console.log(md);
}

if (metaData.filter((p) => p.score < p.total).length > 0 || brokenLinks.length > 0) process.exit(1);
