#!/usr/bin/env node
/**
 * analytics-summary.mjs — Pull Cloudflare Web Analytics data and generate a weekly report.
 *
 * Usage:
 *   CLOUDFLARE_API_TOKEN=xxx CLOUDFLARE_ACCOUNT_ID=yyy \
 *   node tools/growth/analytics-summary.mjs --output ./data/analytics-2026-04-25.md
 *
 * Requires:
 *   CLOUDFLARE_API_TOKEN — Cloudflare API token with Account Analytics:Read permission
 *   CLOUDFLARE_ACCOUNT_ID — Cloudflare account ID
 */

import { parseArgs } from 'node:util';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { config, requireConfig } from '../shared/config.mjs';

const { values } = parseArgs({
  options: {
    output: { type: 'string', default: '' },
    days:   { type: 'string', default: '7' },
    site:   { type: 'string', default: 'dakshna.com' },
  },
  strict: false,
});

requireConfig('cloudflareApiToken', 'cloudflareAccountId');

const days = parseInt(values.days, 10) || 7;
const since = new Date(Date.now() - days * 86400000).toISOString().slice(0, 10);
const until = new Date().toISOString().slice(0, 10);

async function cfGraphQL(query, variables) {
  const res = await fetch('https://api.cloudflare.com/client/v4/graphql', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${config.cloudflareApiToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ query, variables }),
  });
  if (!res.ok) throw new Error(`Cloudflare API error: ${res.status}`);
  const data = await res.json();
  if (data.errors) throw new Error(data.errors.map((e) => e.message).join('; '));
  return data.data;
}

// Cloudflare Web Analytics GraphQL query
const QUERY = `
  query Analytics($accountTag: String!, $since: Date!, $until: Date!) {
    viewer {
      accounts(filter: { accountTag: $accountTag }) {
        rumPageloadEventsAdaptiveGroups(
          filter: { date_geq: $since, date_leq: $until }
          limit: 1000
          orderBy: [count_DESC]
        ) {
          count
          dimensions {
            requestPath
          }
        }
        rumPerformanceEventsAdaptiveGroups(
          filter: { date_geq: $since, date_leq: $until }
          limit: 1
        ) {
          sum {
            visits
            pageViews
          }
          avg {
            pageLoadTime
          }
        }
      }
    }
  }
`;

console.log(`\nFetching Cloudflare Analytics (${since} to ${until})…`);

let data;
try {
  data = await cfGraphQL(QUERY, {
    accountTag: config.cloudflareAccountId,
    since,
    until,
  });
} catch (err) {
  console.error(`Analytics fetch failed: ${err.message}`);
  process.exit(1);
}

const account = data?.viewer?.accounts?.[0];
const pageloadGroups = account?.rumPageloadEventsAdaptiveGroups ?? [];
const perfGroups = account?.rumPerformanceEventsAdaptiveGroups ?? [];

const totalVisits = perfGroups[0]?.sum?.visits ?? 0;
const totalPageViews = perfGroups[0]?.sum?.pageViews ?? 0;
const avgLoadTime = perfGroups[0]?.avg?.pageLoadTime;

// Top pages
const topPages = pageloadGroups
  .sort((a, b) => b.count - a.count)
  .slice(0, 20);

const date = new Date().toISOString().slice(0, 10);
const lines = [
  `# Analytics Summary — ${date}`,
  `_${days}-day window: ${since} to ${until}_`,
  '',
  '## Overview',
  '',
  `| Metric | Value |`,
  `|--------|-------|`,
  `| Visits | ${totalVisits.toLocaleString()} |`,
  `| Page views | ${totalPageViews.toLocaleString()} |`,
  `| Avg load time | ${avgLoadTime ? `${Math.round(avgLoadTime)}ms` : 'N/A'} |`,
  '',
  '## Top Pages',
  '',
  '| Page | Views |',
  '|------|-------|',
  ...topPages.map((p) => `| \`${p.dimensions.requestPath}\` | ${p.count.toLocaleString()} |`),
  '',
  `---`,
  `_Generated by tools/growth/analytics-summary.mjs_`,
];

const md = lines.join('\n');

if (values.output) {
  mkdirSync(dirname(values.output), { recursive: true });
  writeFileSync(values.output, md + '\n', 'utf8');
  console.log(`Report saved → ${values.output}`);
} else {
  console.log(md);
}
